name: "check piplines"

on: 
  push:
      branches:
          - cicd
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up npm
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: install dependecies
        run: npm install
      - name: run tests
        run: npm run test
      - name: print success message
        run: echo 'Success! all the tests passed, the deployement could be done'
      - name: Install amplify
        run: npm install -g @aws-amplify/cli 
      - name: publish steps
        run: amplify push --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
      - name: is publiched success
        run: echo "version published successly ! :rocket:"




